### ISSUE TITLE
Module Twin in Orchestrator not working

### ISSUE THREAD

**Issue by Peter-B-** [paloukari/TypeEdge.AnomalyDetection#23]
Hi

I managed to get the project running and I can access the web UI. But when I try to set the routing mode of the Orchestrator through its module twin in the ServiceApp, the twin subscription inside the ```Orchestrator``` class is not invoked.

In the console output of the Emulator I see 
```[ERR] - Module type-edge-dev/orchestrator is not connected```
pop up 4 times. But I cannot find any other hints of something going wrong.

Do you have any idea?

**Comment by paloukari** [comment]
IoT Edge uses RockDB to store and forward the messages. Sometimes, if you kill the running app, some messages are left in the database as unprocessed. I've noticed that this may become a problem when you restart the app. Try deleting the bin folder, this will get rid of the old database and in the next run, a new one. will be created.
Let me know if that helped.

**Comment by Peter-B-** [comment]
I just ran the example on my private computer and everything works fine. 
I will try deleting bin on the other machine tomorrow.

Thanks for the leg up
